export const messageAction = {
    SET_SUCCESS_MESSAGE: "SET_SUCCESS_MESSAGE",
    REMOVE_SUCCESS_MESSAGE: "REMOVE_SUCCESS_MESSAGE",
    SET_ERROR_MESSAGE: "SET_ERROR_MESSAGE",
    REMOVE_ERROR_MESSAGE: "REMOVE_ERROR_MESSAGE"
};